version: '3.2'
services:
  pg:
    image: postgres:13.2
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: lingvodoc
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
  nginx:
    image: nginx:latest
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/dist
      - ./nginx:/etc/nginx/conf.d
      - ./sock:/sock
      - /tmp:/tmp
    depends_on:
      - pg
      - api
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '16379:6379'
  api:
    build: ..
    depends_on:
      - pg
      - redis
    links:
      - pg
      - redis

    container_name: ld
    volumes:
      - ./frontend/dist:/dist
      - ./sock:/sock
      - /api/build/
      - ../:/api
      - /tmp:/tmp

    env_file:
      - ./locale_env.sh
    command: bash -c "python3 setup.py clean && python3 setup.py install --react-interface=/dist && /api/wait-for-postgres.sh pg && alembic --config /api/docker/docker-alembic.ini upgrade head && pserve /api/docker/docker.ini"
    ports:
      - "16543:6543"
