version: '3.2'
services:
  pg:
    image: postgres:13.2
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: lingvodoc
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
  pg-proxy:
    image: postgres:13.2
    container_name: postgres-proxy
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: lingvodoc
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
    ports:
      - "25432:5432"
  nginx:
    image: nginx:latest
    container_name: ngx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/dist
      - ./nginx:/etc/nginx/conf.d
      - ./sock:/sock
      - /tmp:/tmp
    depends_on:
      - pg
      - api
  nginx-proxy:
    image: nginx:latest
    container_name: ngx-proxy
    ports:
      - "1080:80"
      - "1443:443"
    volumes:
      - ./frontend-proxy/dist:/dist
      - ./nginx:/etc/nginx/conf.d
      - ./sock-proxy:/sock
      - /tmp:/tmp
    depends_on:
      - pg-proxy
      - api-proxy
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '16379:6379'
  redis-proxy:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '26379:6379'
  api:
    build: ..
    depends_on:
      - pg
      - redis
    links:
      - pg
      - redis
      
    container_name: ld
    volumes:
      - ./frontend/dist:/dist
      - /opt/apertium:/opt/apertium
      - /opt/hfst:/opt/hfst
      - ./sock:/sock
      - /api/build/
      - ../:/api
      - /tmp:/tmp

    env_file:
      - ./locale_env.sh
    command: bash -c "python3 setup.py clean && python3 setup.py install --react-interface=/dist && /api/wait-for-postgres.sh pg && git config --global --add safe.directory /api && alembic --config /api/docker/docker-alembic.ini upgrade head && gunicorn --paster /api/docker/docker.ini"
    ports:
      - "16543:6543"
  api-proxy:
    build: ..
    depends_on:
      - pg-proxy
      - redis-proxy
    links:
      - pg-proxy
      - redis-proxy
      
    container_name: ld-proxy
    volumes:
      - ./frontend-proxy/dist:/dist
      - /opt/apertium:/opt/apertium
      - /opt/hfst:/opt/hfst
      - ./sock-proxy:/sock
      - /api/build/
      - ../:/api
      - /tmp:/tmp

    env_file:
      - ./locale_env.sh
    command: bash -c "python3 setup.py clean && python3 setup.py install --react-interface=/dist && /api/wait-for-postgres.sh pg-proxy && git config --global --add safe.directory /api && alembic --config /api/docker/docker-alembic-proxy.ini upgrade head && gunicorn --paster /api/docker/docker-proxy.ini"
    ports:
      - "26543:6543"
